title: johannes klabbers
author:
  name:
  email:
  description: i am here (1958—2044)

permalink: pretty

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:

    rss: rss

#
# -

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-gist
 - jekyll-seo-tag
 - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

header_pages:
  - about.md
  - now.md
  - posts.md
  - pinboard.md

include: ['_pages'] 